In [11]:
#Importing the libraries

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import pandas as pd
from sklearn import datasets
from sklearn import metrics
from enum import auto
from sklearn.svm import SVC

#Uploading dataset
dataset = pd.read_csv("Credit.csv")
X= dataset.iloc[:,:-1].values
y= dataset.iloc[:,24].values

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 82)

# Feature Scaling to bring the variable in a single scale
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [3]:
#logistic regression

print("\n Logistic Regression ")

from sklearn.linear_model import LogisticRegression
logisticregression = LogisticRegression()
logisticregression.fit(X_train, y_train)

# Predicting the Test set results
y_pred = logisticregression.predict(X_test)
print(y_pred)

#lets see the actual and predicted value side by side
y_compare = np.vstack((y_test,y_pred)).T

#actual value on the left side and predicted value on the right hand side
#printing the top 5 values
y_compare[:5,:]

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
print ("Model Accuracy Logistic Regression: ",accuracy_score(y_test, y_pred))
print("Classification Report Logistic Regression: \n", metrics.classification_report(y_test, y_pred))
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix Logistic Regression: \n",cm)


 Logistic Regression 
[0 1 0 ... 0 1 0]
Model Accuracy Logistic Regression:  0.8149333333333333
Classification Report Logistic Regression: 
               precision    recall  f1-score   support

           0       0.82      0.97      0.89      5880
           1       0.72      0.24      0.36      1620

    accuracy                           0.81      7500
   macro avg       0.77      0.61      0.62      7500
weighted avg       0.80      0.81      0.78      7500

Confusion Matrix Logistic Regression: 
 [[5728  152]
 [1236  384]]


In [4]:
#Applying SVM Algorithm

print("\n")
print("\n SVM")

# set model, fit and predict
from sklearn.svm import SVC
svm = SVC(kernel='rbf')
svm.fit(X_train, y_train)

# Predicting the Test set results
y_prediction = svm.predict(X_test)
print(y_prediction)

#lets see the actual and predicted value side by side
y_compare = np.vstack((y_test,y_prediction)).T

#actual value on the left side and predicted value on the right hand side
#printing the top 5 values
y_compare[:5,:]

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
print ("Model Accuracy SVM: ",accuracy_score(y_test, y_prediction))
print("Classification Report SVM: \n",metrics.classification_report(y_test, y_prediction))
cm = confusion_matrix(y_test, y_prediction)
print("Confusion Matrix SVM: \n",cm)





 SVM
[0 1 0 ... 0 1 1]
Model Accuracy SVM:  0.822
Classification Report SVM: 
               precision    recall  f1-score   support

           0       0.84      0.96      0.89      5880
           1       0.68      0.33      0.44      1620

    accuracy                           0.82      7500
   macro avg       0.76      0.64      0.67      7500
weighted avg       0.80      0.82      0.80      7500

Confusion Matrix SVM: 
 [[5636  244]
 [1091  529]]


In [5]:
#Applying Rndom Forest

print("\n")
print("\n Rndom Forest")

from sklearn.ensemble import RandomForestClassifier
# set model, fit and predict
rfc = RandomForestClassifier(max_depth=10, random_state=0)
rfc.fit(X_train, y_train)

# Predicting the Test set results
y_prediction = rfc.predict(X_test)
print(y_prediction)

#lets see the actual and predicted value side by side
y_compare = np.vstack((y_test,y_prediction)).T

#actual value on the left side and predicted value on the right hand side
#printing the top 5 values
y_compare[:5,:]

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score

print ("Model Accuracy Rndom Forest: ", accuracy_score(y_test, y_prediction))
print("Classification Report Rndom Forest: \n", metrics.classification_report(y_test, y_prediction))
print("Confusion Matrix Rndom Forest: \n", metrics.confusion_matrix(y_test, y_prediction))




 Rndom Forest
[0 1 0 ... 0 1 1]
Model Accuracy Rndom Forest:  0.8221333333333334
Classification Report Rndom Forest: 
               precision    recall  f1-score   support

           0       0.84      0.95      0.89      5880
           1       0.67      0.35      0.46      1620

    accuracy                           0.82      7500
   macro avg       0.76      0.65      0.68      7500
weighted avg       0.80      0.82      0.80      7500

Confusion Matrix Rndom Forest: 
 [[5599  281]
 [1053  567]]


In [6]:
#APPLYING KNN

print("\n")
print("\n KNN")

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier()

classifier.fit(X_train, y_train)


predictions = classifier.predict(X_test)
from sklearn.metrics import accuracy_score
print (accuracy_score(y_test, predictions))

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
print ("Model Accuracy KNN: ", accuracy_score(y_test, predictions))
print("Classification Report KNN: \n", metrics.classification_report(y_test, predictions))
print("Confusion Matrix KNN: \n",metrics.confusion_matrix(y_test, predictions))




 KNN
0.7962666666666667
Model Accuracy KNN:  0.7962666666666667
Classification Report KNN: 
               precision    recall  f1-score   support

           0       0.84      0.92      0.88      5880
           1       0.55      0.34      0.42      1620

    accuracy                           0.80      7500
   macro avg       0.69      0.63      0.65      7500
weighted avg       0.77      0.80      0.78      7500

Confusion Matrix KNN: 
 [[5418  462]
 [1066  554]]


In [7]:
#Applying ANN

print("\n")
print("\n ANN")

import keras
from keras.models import Sequential
from keras.layers import Dense

classifier = Sequential()

classifier.add(Dense(12, activation= 'relu',input_dim=24))

classifier.add(Dense(7, activation= 'relu'))

classifier.add(Dense(1, activation= 'sigmoid'))


classifier.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

classifier.fit(X_train, y_train,batch_size=10, epochs=100)

#predicting the test set result

y_pred=classifier.predict(X_test)
y_pred=(y_pred>0.5)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
print("Classification Report ANN: \n", metrics.classification_report(y_test,y_pred))
print("Confusion Matrix ANN: \n",metrics.confusion_matrix(y_test,y_pred ))






 ANN
Epoch 1/100


/opt/anaconda3/lib/python3.12/site-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


2250/2250 ━━━━━━━━━━━━━━━━━━━━ 1s 215us/step - accuracy: 0.7757 - loss: 0.5233
Epoch 2/100
2250/2250 ━━━━━━━━━━━━━━━━━━━━ 0s 213us/step - accuracy: 0.8099 - loss: 0.4539
Epoch 3/100
2250/2250 ━━━━━━━━━━━━━━━━━━━━ 0s 217us/step - accuracy: 0.8133 - loss: 0.4429
Epoch 4/100
2250/2250 ━━━━━━━━━━━━━━━━━━━━ 0s 214us/step - accuracy: 0.8237 - loss: 0.4298
Epoch 5/100
2250/2250 ━━━━━━━━━━━━━━━━━━━━ 0s 218us/step - accuracy: 0.8157 - loss: 0.4388
Epoch 6/100
2250/2250 ━━━━━━━━━━━━━━━━━━━━ 0s 214us/step - accuracy: 0.8180 - loss: 0.4299
Epoch 7/100
2250/2250 ━━━━━━━━━━━━━━━━━━━━ 0s 217us/step - accuracy: 0.8227 - loss: 0.4253
Epoch 8/100
2250/2250 ━━━━━━━━━━━━━━━━━━━━ 0s 216us/step - accuracy: 0.8194 - loss: 0.4297
Epoch 9/100
2250/2250 ━━━━━━━━━━━━━━━━━━━━ 0s 218us/step - accuracy: 0.8188 - loss: 0.4283
Epoch 10/100
2250/2250 ━━━━━━━━━━━━━━━━━━━━ 0s 217us/step - accuracy: 0.8213 - loss: 0.4257
Epoch 11/100
2250/2250 ━━━━━━━━━━━━━━━━━━━━ 0s 217us/step - accuracy: 0.8207 - loss: 0.4296
Epoch 12/